export enum Industry {
  AutoMobile = "Auto Mobile",
  ECommerce = "E-Commerce",
  HealthCare = "Health Care",
  Manufacturing = "Manufacturing",
  RealEstate = "Real Estate",
  Travel = "Travel",
  ArtsEntertainment = "Arts & Entertainment",
  BusinessIndustrial = "Business & Industrial",
  Education = "Education",
  Electronics = "Electronics",
  Finance = "Finance",
  FoodBeverages = "Food and Beverages",
  Hardware = "Hardware",
  HealthBeauty = "Health & Beauty",
  HomeGarden = "Home & Garden",
  HRConsultant = "HR Consultant",
  Media = "Media",
  NGO = "NGO",
  ReligiousCeremonial = "Religious & Ceremonial",
  Software = "Software",
  SportingGoods = "Sporting Goods",
  TaxConsultants = "Tax Consultants",
  ToursTravel = "Tours & Travel",
  VehiclesParts = "Vehicles & Parts",
  Other = "Other",
}
